import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <nav className="bg-white border-b">
          <div className="max-w-5xl mx-auto p-4 flex gap-4">
            <a href="/" className="font-medium text-black">Dashboard</a>
            <a href="/wardrobe" className="font-medium text-black">Wardrobe</a>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
